api/urls.py
from django.urls import path, include
#APP
from api.views.authentication_views.auth_views import RegistrationView, ValidateEmailView, CertificatePhoneView, ValidateSMSCertificationNumberView, FindEmailView

app_name='api'
urlpatterns = [
    path('registration/', RegistrationView.as_view()),
    path('validate-email/', ValidateEmailView.as_view()),
    path('certificate-phone/', CertificatePhoneView.as_view()),
    path('validate-sms-certification-number/', ValidateSMSCertificationNumberView.as_view()),
    path('find-email/', FindEmailView.as_view()),
]

config/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('api/', include('api.urls')),
    path('system-manage/', include('system_manage.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

system_manage/urls.py
from django.urls.conf import path
from django.contrib.auth.views import LogoutView

from system_manage.views.system_manage_views.auth_views import HomeView, LoginView, PermissionDeniedView, NotFoundView

app_name = 'system_manage'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='system_manage:login'), name='logout'),
    path('denied/', PermissionDeniedView.as_view(), name='denied'),
    path('notfound/', NotFoundView.as_view(), name='notfound'),
]

website/maps/urls.py
from django.urls import path
from .views import map_view

urlpatterns = [
    path('map/', map_view, name='map'),
]

website/urls.py
from django.urls.conf import path
from django.contrib.auth.views import LogoutView
from website.views.authentication_views.auth_views import HomeView
from website.views.authentication_views.auth_views import HomeView, LoginView, RegistrationView, CertificatePhoneView, FindEmailView, ActivationConfirmView, activate
from website.views.authentication_views.password_reset_views import UserPasswordResetView, UserPasswordResetDoneView, CustomPasswordResetConfirmView, UserPasswordResetCompleteView

app_name = 'website'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='website:home'), name='logout'),
    path('registration/', RegistrationView.as_view(), name='registration'),
    path('certificate-phone/', CertificatePhoneView.as_view(), name='certificate_phone'),
    path('activation-confirm/', ActivationConfirmView.as_view(), name='activation_confirm'),
    path('activate/<str:uidb64>/<str:token>/', activate, name="activate"),
    path('find-email/', FindEmailView.as_view(), name='find_email'),

    path('password-reset/', UserPasswordResetView.as_view(), name='password_reset'),
    path('password-reset-done/', UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('password-reset-complete/', UserPasswordResetCompleteView.as_view(), name="password_reset_complete"),


]

system_manage/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from django.shortcuts import redirect


class State(models.Model):
    name = models.CharField(max_length=50, verbose_name='이름')
    alpha_code = models.CharField(max_length=10, verbose_name='알파벳 코드', unique=True)

    class Meta:
        db_table='state'

#문자인증
class SMSCertification(models.Model):
    phone = models.CharField(max_length=30, verbose_name='전화번호')
    certification_number = models.CharField(max_length=10, verbose_name='인증번호')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='생성일')

    class Meta:
        db_table='sms_certification'

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    membername = models.CharField(null=True, max_length=50, verbose_name='회원명')
    phone = models.CharField(unique=True, max_length=30, verbose_name='전화번호')
    gender = models.CharField(default='M', max_length=10, verbose_name='성별') # M / F
    birth = models.DateField(null=True, verbose_name='생년월일')

    state = models.ForeignKey(State, on_delete=models.PROTECT, null=True)
    city = models.CharField(null=True, max_length=30, verbose_name='도시')
    zipcode = models.CharField(null=True, max_length=10, verbose_name='우편번호')
    oauth_type = models.CharField(default=None, max_length=20, verbose_name='oauth type') # google, facebook
    withdrawal_at = models.DateTimeField(null=True, verbose_name='탈퇴일')
    email_verified = models.BooleanField(default=False, verbose_name='이메일 인증여부')

    point = models.PositiveIntegerField(default=0, verbose_name='사용자 포인트')

    class Meta:
        db_table='auth_profile'


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance, oauth_type='')

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


def my_login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return 'user_main.html'
        else:
            return HttpResponse("Invalid login details.")
        
def my_logout_view(request):
    logout(request)
    return 'user_login.html'

class Partner(models.Model):
    name = models.CharField(max_length=100)

class PaymentRecord(models.Model):
    date = models.DateField()
    partner = models.ForeignKey(Partner, on_delete=models.CASCADE)
    beginning_balance = models.DecimalField(max_digits=10, decimal_places=2)
    claim = models.DecimalField(max_digits=10, decimal_places=2)
    ending_balance = models.DecimalField(max_digits=10, decimal_places=2)
    paid_claim = models.DecimalField(max_digits=10, decimal_places=2)
    claim_balance = models.DecimalField(max_digits=10, decimal_places=2)
    

website/maps/views.py
from django.shortcuts import render
from .models import PaymentRecord

def map_view(request):
    return render(request, 'map.html', {'AIzaSyAgekxD1j7QjNQDhAO1MO6xJYFkgajc7x4': settings.GOOGLE_MAPS_API_KEY})

def payment_list(request):
    records = PaymentRecord.objects.all()
    return render(request, 'user_main.html', {'records': records})

system_manage/templates/system_manage/permission_denied.html
{% extends "layouts/system_base.html" %}
{% load static %}

{% block body %}

<main>
    <div class="container">

      <section class="section error-404 min-vh-100 d-flex flex-column align-items-center justify-content-center">
        <h1>Access Denied</h1>
        <br>
        <br>
        <h2>{{user.profile.username}}, you don't currently have permission to access this page.</h2>
        <div class="row">
          <div class="col">
            <a class="btn" href="{% url 'system_manage:home' %}">Home</a>
          </div>
          <div class="col">
            <a class="btn" href="{% url 'system_manage:logout' %}">Logout</a>
          </div>
        </div>
        <p class="small m-3">관리자가 아니신가요?<a class="ms-1" href="{% url 'website:home' %}">돌아가기</a></p>

        <img src="{% static 'system/assets/img/not-found.svg' %}" class="img-fluid py-5" alt="Page Not Found">
        <div class="credits">
        </div>
      </section>

    </div>
  </main><!-- End #main -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>
{% endblock %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
{% endblock javascripts %}

templates/includes/system/header.html
{% load static %}
<!-- ======= Header ======= -->
 <header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
      <a href="{% url 'system_manage:home' %}" class="logo d-flex align-items-center">
        <span class="d-none d-lg-block">{{global_site_name}} Admin</span>
      </a>
      <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->

    <nav class="header-nav ms-auto">
      <ul class="d-flex align-items-center">
        <li class="nav-item dropdown pe-3">
          <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
            <span class="d-none d-md-block dropdown-toggle p-2">{{user}}</span>
          </a><!-- End Profile Iamge Icon -->
          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
            <li class="dropdown-header">
              <h6>{{user}}</h6>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>
            <li>
              <a class="dropdown-item d-flex align-items-center" href="{% url 'system_manage:logout' %}" onclick="return confirm('로그아웃 하시겠습니까?');">
                <i class="bi bi-box-arrow-right"></i>
                <span>Sign Out</span>
              </a>
            </li>
          </ul><!-- End Profile Dropdown Items -->
        </li><!-- End Profile Nav -->

      </ul>
    </nav><!-- End Icons Navigation -->

  </header><!-- End Header -->

templates/includes/system/sidebar.html
 <!-- ======= Sidebar ======= -->
 <aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">

      <li class="nav-item">
        <a class="nav-link " href="{% url 'system_manage:home' %}">
          <i class="bi bi-grid"></i>
          <span>Dashboard</span>
        </a>
      </li><!-- End Dashboard Nav -->
      <li class="nav-heading">User</li>
      <li class="nav-item"> 
        <a class="nav-link collapsed" href="#"> <i class="bi bi-person-fill"></i> <span>회원 관리</span> </a>
      </li>
    </ul>

  </aside><!-- End Sidebar-->

templates/includes/website/header.html
{% load static %}
<!-- ======= Header ======= -->
<header id="header" class="fixed-top d-flex align-items-center  header-transparent ">
    <div class="container d-flex align-items-center justify-content-between">

      <div class="logo">
        <a href="/"><img src="/static/website/assets/img/pagee_logo.png" alt="Pagee_logo"></a>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
      </div>

      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link scrollto active" href="#Sangvo Pay">Sangvo Pay</a></li>
          <!-- <li><a class="nav-link scrollto" href="#Sangvo Management">Sangvo MGT</a></li> -->
          <li><a class="nav-link scrollto" href="#Ads Play Condition">Ads Play Condition</a></li>
          <!-- <li><a class="nav-link scrollto" href="#M Sangvo E&U STM">M Sangvo E&U STM</a></li> -->
          <!-- <li><a class="nav-link scrollto" href="#Member List">Member List</a></li> -->
          <li><a class="nav-link scrollto" href="#Partner List">Partner List</a></li>
          <!-- <li><a class="nav-link scrollto" href="#Patner SV Summary">Partner SV Summary(Daily)</a></li> -->
          <!-- <li><a class="nav-link scrollto" href="#Sangvo Table">Sangvo Table</a></li> -->
          {% if request.user.is_authenticated %}
            <ul>
              <li><a href="{% url 'website:logout' %}" onclick="return confirm('로그아웃 하시겠습니까?');">Logout</a></li>
            </ul>
          </li>
          {% else %}
          <li><a class="nav-link scrollto" href="{% url "website:login" %}">Login</a></li>
          {% endif %}
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->

website/templates/authentication/activation_email.html
{% autoescape off %}

{{user.username}}

Please use the link below to complete the BuildPay email authentication process.

http://{{domain}}{% url 'website:activate' uidb64=uid token=token %}


{% endautoescape %}

website/templates/authentication/password_reset.html
{% extends "layouts/website_base.html" %}
{% load static %}
{% block stylesheets %}
<style>
  #header.header-transparent {
    background: rgba(49, 51, 70, 0.9);
    padding: 12px 0;
  }

  .btn-custom {
    padding: 12px 40px;
    border-radius: 50px;
    transition: 0.5s;
    color: #fff;
    background: rgba(239, 102, 3);
  }

  .btn-custom:hover {
    background: var(--color-rgba(239, 102, 3));
  }
</style>
{% endblock stylesheets %}

{% block main %}
<main id="main">
  <section class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-6 col-md-6 d-flex flex-column align-items-center justify-content-center">
          <div class="card mb-3">
            <div class="card-body">
              <div class="pt-4 pb-2">
                <h5 class="card-title text-center pb-0 fs-4">Reset Password</h5>
                <p class="text-center small">Enter your email to reset your password</p>
              </div>
              <form  method='post' action="{% url 'website:password_reset' %}" id='resetform'>
                {% csrf_token %}
                <div class="row gy-3">
                  <div class="col-md-12 form-group">
                    <label for="email">Email</label>
                    <input type="email" name="email" class="form-control" id="email" placeholder="email">
                  </div>
                  
                  <div class="col-12 mt-4 form-group" id="btn-submit-container">
                    <a class="btn-custom w-100 text-center" type="button" id="btn-submit" onclick="document.getElementById('resetform').submit();return false;">Next</a>
                  </div>
  
                  <div class="col-md-12 mt-4 form-group">
                    <p class="small mb-0 text-end">
                      <a class="ms-1 link-dark" href="{% url "website:login" %}">Login</a>
                      &middot;
                      <a class="ms-1 text-dark" href="{% url "website:find_email" %}">Find email &gt;</a>
                    </p>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
    </div>
  </section>
</main>
{% endblock %}
{% block javascripts %}
{% endblock javascripts %}

website/templates/authentication/password_reset_complete.html
{% extends "layouts/website_base.html" %}
{% load static %}
{% block stylesheets %}
<style>
  #header.header-transparent {
    background: rgba(49, 51, 70, 0.9);
    padding: 12px 0;
  }

  .btn-custom {
    padding: 12px 40px;
    border-radius: 50px;
    transition: 0.5s;
    color: #fff;
    background: rgba(239, 102, 3);
  }

  .btn-custom:hover {
    background: var(--color-rgba(239, 102, 3));
  }
</style>
{% endblock stylesheets %}

{% block main %}
<main id="main">
  <section class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-6 col-md-6 d-flex flex-column align-items-center justify-content-center">
          <h5 class="card-title text-center pb-0 fs-4 mb-3">비밀번호가 변경되었습니다.</h5>
          <h5 class="card-title text-center pb-0 fs-4 mb-3">새로운 비밀번호로 로그인 해주세요.</h5>
          <div class="col-12 mt-4 form-group" id="btn-submit-container">
            <a class="btn-custom w-100 text-center" type="button" id="btn-submit"
              href="{% url "website:login" %}">login</a>
            </div>
            <div class="col-md-12 mt-4 form-group">
              <p class="small mb-0 text-end">
                <a class="ms-1 text-dark" href="{% url "website:find_email" %}">ID 찾기 &gt;</a>
              </p>
            </div>
        </div>
      </div>
    </div>
    </div>
  </section>
</main>
{% endblock %}
{% block javascripts %}
{% endblock javascripts %}

website/templates/authentication/password_reset_done_fail.html
{% extends "layouts/website_base.html" %}
{% load static %}
{% block stylesheets %}
<style>
  #header.header-transparent {
    background: rgba(49, 51, 70, 0.9);
    padding: 12px 0;
  }

  .btn-custom {
    padding: 12px 40px;
    border-radius: 50px;
    transition: 0.5s;
    color: #fff;
    background: rgba(239, 102, 3);
  }

  .btn-custom:hover {
    background: var(--color-rgba(239, 102, 3));
  }
</style>
{% endblock stylesheets %}

{% block main %}
<main id="main">
  <section class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-6 col-md-6 d-flex flex-column align-items-center justify-content-center">
          <h5 class="card-title text-center pb-0 fs-4 mb-3">잘못된 사용자 정보입니다.</h5>
          <h5 class="card-title text-center pb-0 fs-4 mb-3">입력하신 정보를 확인해 주세요.</h5>
          <div class="col-12 mt-4 form-group" id="btn-submit-container">
            <a class="btn-custom w-100 text-center" type="button" id="btn-submit"
              href="{% url "website:password_reset" %}">Retry</a>
            </div>
            <div class="col-md-12 mt-4 form-group">
              <p class="small mb-0 text-end">
                <a class="ms-1 link-dark" href="{% url "website:login" %}">login</a>
                &middot;
                <a class="ms-1 text-dark" href="{% url "website:find_email" %}">ID 찾기 &gt;</a>
              </p>
            </div>
        </div>
      </div>
    </div>
    </div>
  </section>
</main>
{% endblock %}
{% block javascripts %}
{% endblock javascripts %}

website/templates/authentication/password_reset_email.html
{% autoescape off %}

{{user.get_username}}

To reset Password, complete it through the link below.

{{ protocol }}://{{domain}}{% url 'website:password_reset_confirm' uidb64=uid token=token %}

If the link is not clicked, copy and paste the address above into your browser.

{% endautoescape %}

website/templates/authentication/user_certificate_phone.html
{% extends "layouts/website_base.html" %}
{% load static %}
{% block stylesheets %}
<style>
  #header.header-transparent {
    background: rgba(49, 51, 70, 0.9);
    padding: 12px 0;
  }

  .btn-custom {
    padding: 12px 40px;
    border-radius: 50px;
    transition: 0.5s;
    color: #fff;
    background: rgba(239, 102, 3);
  }

  .btn-custom:hover {
    background: var(--color-rgba(239, 102, 3));
  }
</style>


{% endblock stylesheets %}

{% block main %}
<main id="main">
  <section class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-6 col-md-6 d-flex flex-column align-items-center justify-content-center">
          <div class="card mb-3">
            <div class="card-body">

              <div class="pt-4 pb-2">
                <h5 class="card-title text-center pb-0 fs-4">SMS Certification</h5>
                <p class="text-center small">Enter your phone number</p>
              </div>
              <div class="row g-3">
                <div class="col-md-9 form-group">
                  <label for="phone">Phone</label>
                  <input type="number" class="form-control" name="phone" id="phone" placeholder="" maxlength="10" min="0" oninput="maxLengthCheck(this)">
                </div>
                <div class="col-md-3 form-group text-end">
                  <input type="button" class="btn btn-secondary mt-4" value="Send" id="btn_certificate_phone"
                    onclick="certificatePhone(this);">
                </div>
                <div id="sms_certification_div" class="mt-3 d-none">
                  <div class="row">                    
                    <div class="col-md-9 form-group">
                      <input type="number" class="form-control" name="sms_certification_number"
                      id="sms_certification_number" placeholder="xxxxxx" maxlength="6" min="0"
                      oninput="maxLengthCheck(this)">
                    </div>
                    <div class="col-md-3 form-group text-end">
                      <input type="button" class="btn btn-secondary" value="check" id="btn_certificate_phone"
                      onclick="certificateNumber(this);">
                    </div>
                    <div class="col-md-12 form-group text-start" id="expiration_time">
                    </div>
                  </div>
                </div>
                <div class="col-12 mt-4">
                  <input type="hidden" id="register-url">
                  <input type="hidden" id="certificated-phone">
                  <a href="javascript:;" class="btn-custom w-100 text-center d-none" type="button" id="btn-next" onclick="getRegisterPage();">Next</a>
                </div>
                <div class="col-md-12 mt-4 form-group">
                  <p class="small mb-0 text-end">
                    <a class="ms-1 link-dark" href="{% url "website:login" %}">Login</a>
                    &middot;
                    <a class="ms-1 text-dark" href="{% url "website:find_email" %}">Find email</a> / <a class="ms-1 text-dark" href="{% url "website:password_reset" %}">Rest Password &gt;</a>
                  </p>
                </div>
              </div>

            </div>
          </div>
        </div>
      </div>
    </div>
    </div>
  </section>
</main>
{% endblock %}
{% block javascripts %}
<script src="{% static 'website/js/auth/script_user_certificate_phone.js' %}"></script>
{% endblock javascripts %}

website/templates/authentication/user_login.html
{% extends "layouts/website_base.html" %}
{% load static %}
{% block stylesheets %}
<style>
  #header.header-transparent {
    background: rgba(49, 51, 70, 0.9);
    padding: 12px 0;
  }

  .btn-custom {
    padding: 12px 40px;
    border-radius: 50px;
    transition: 0.5s;
    color: #fff;
    background: rgba(239, 102, 3);
  }

  .btn-custom:hover {
    background: var(--color-rgba(239, 102, 3));
  }
</style>
{% endblock stylesheets %}

{% block main %}
<main id="main">
  <section class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-5 col-md-6 d-flex flex-column align-items-center justify-content-center">
          <div class="card mb-3">
            <div class="card-body">

              <div class="pt-4 pb-2">
                <h5 class="card-title text-center pb-0 fs-4">Login</h5>
                <p class="text-center small">Enter your Email & Password to Login</p>
              </div>

              <form class="row g-3 needs-validation" id="loginForm">

                <div class="col-12">
                  <label for="email" class="form-label">Email</label>
                  <div class="input-group has-validation">
                    <input type="text" name="email" class="form-control" id="email" placeholder="Email" required
                      onkeyup="enterkey(this)">
                  </div>
                </div>

                <div class="col-12 mb-3">
                  <label for="password" class="form-label">Password</label>
                  <input type="password" name="password" class="form-control" id="password" placeholder="Password"
                    required onkeyup="enterkey(this)">
                </div>
                <div class="col-12">
                  <a class="btn-custom w-100 text-center" type="button" id="btn-login">Login</a>
                </div>
                <div class="col-md-12 mt-4 form-group">
                  <p class="small mb-0 text-end">
                    <a class="ms-1 link-dark" href="{% url "website:certificate_phone" %}">Join</a>
                    &middot;
                    <a class="ms-1 text-dark" href="{% url "website:find_email" %}">Find email<a> / <a class="ms-1 text-dark"
                          href="{% url "website:password_reset" %}">Reset Password &gt;</a>
                  </p>
                </div>
            </div>
            </form>
          </div>
        </div>
      </div>
    </div>
    </div>
  </section>
</main>
{% endblock %}
{% block javascripts %}
<script src="{% static 'website/js/auth/script_user_login.js' %}"></script>
{% endblock javascripts %}

website/templates/authentication/user_registration.html
{% extends "layouts/website_base.html" %}
{% load static %}
{% block stylesheets %}
<style>
  #header.header-transparent {
    background: rgba(49, 51, 70, 0.9);
    padding: 12px 0;
  }

  .btn-custom {
    padding: 12px 40px;
    border-radius: 50px;
    transition: 0.5s;
    color: #fff;
    background: rgba(239, 102, 3);
  }

  .btn-custom:hover {
    background: var(--color-rgba(239, 102, 3));
  }
</style>
{% endblock stylesheets %}

{% block main %}
<main id="main">
  <section class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4">
    <div class="container">
      <div class="row justify-content-center" style="margin-top:100px;">
        <div class="col-lg-6 col-md-6 d-flex flex-column align-items-center justify-content-center">
          <div class="card">
            <div class="card-body">

              <div class="pt-4 pb-2 mb-4">
                <h5 class="card-title text-center pb-0 fs-4">Sign Up</h5>
              </div>

              <form method="post" id="registrationForm" class="php-email-form">
                <div class="row gy-3">

                  <div class="col-md-5 form-group">
                    <label for="first-name" class="form-label">First Name</label>
                    <input type="text" name="first_name" class="form-control" id="first-name" placeholder="First Name"
                      required>
                  </div>
                  <div class="col-md-5 form-group">
                    <label for="last-name" class="form-label">Last Name</label>
                    <input type="text" name="last_name" class="form-control" id="last-name" placeholder="Last Name"
                      required>
                  </div>
                  <div class="col-md-2 form-group">
                    <label for="gender" class="form-label">Gender</label>
                    <select name="gender" id="gender" class="form-select">
                      <option value="M">M</option>
                      <option value="Y">Y</option>
                    </select>
                  </div>

                  <div class="col-md-12 form-group">
                    <label for="birth">Birth</label>
                    <input type="date" class="form-control" name="birth" id="birth" placeholder="birth">
                  </div>

                  <div class="col-md-8 form-group">
                    <label for="email">Email</label>
                    <input type="email" class="form-control" name="email" id="email" placeholder="Email">
                  </div>
                  <div class="col-md-4 form-group text-end">
                    <input type="button" class="btn btn-secondary mt-4" id="btn-email" value="check duplication" onclick="checkEmail(this);">
                  </div>
                  <div class="col-md-12 form-group">
                    <label for="password1">Password</label>
                    <input type="password" class="form-control" name="password" id="password1" placeholder="Password">
                  </div>
                  <div class="col-md-12 form-group">
                    <label for="password2">Confirm Password </label>
                    <input type="password" class="form-control" id="password2"
                      placeholder="Confirm Password">
                  </div>
                  <div class="col-md-12 form-group">
                    <label for="phone">Phone</label>
                    <input type="number" name="phone" class="form-control" id="phone" value="{{phone}}" placeholder="xxxxxxxxxx" readonly>
                  </div>
                  <div class="col-md-7 form-group">
                    <label for="city" class="form-label">City</label>
                    <input type="text" name="city" class="form-control" id="city" placeholder="City" required>
                  </div>

                  <div class="col-md-5 form-group">
                    <label for="state" class="form-label">State</label>
                    <select name="state" id="state" class="form-select">
                      {% for i in state %}
                      <option value="{{i.alpha_code}}">{{i.name}}</option>
                      {% endfor %}
                    </select>
                  </div>

                  <div class="col-md-5 form-group">
                    <label for="zip-code" class="form-label">Zip Code</label>
                    <input type="number" name="zipcode" class="form-control" id="zip-code" placeholder="Zip Code"
                      required>
                  </div>

                  <div class="col-12 mt-3 form-group">
                    <a class="btn-custom w-100 text-center" type="button" id="btn-submit">Join</a>
                  </div>

                  <div class="col-md-12 mt-3 form-group">
                    <p class="small mb-0 text-end">
                      <a class="ms-1 link-dark" href="{% url 'website:login' %}">Login</a>
                      &middot;
                      <a class="ms-1 text-dark" href="{% url "website:find_email" %}">Find email</a> / <a class="ms-1 text-dark" href="{% url "website:password_reset" %}">Rest Password &gt;</a>
                    </p>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</main>
{% endblock %}
{% block javascripts %}
<script src="{% static 'website/js/auth/script_user_registration.js' %}"></script>
{% endblock javascripts %}